### ISSUE TITLE
Can you pleae make it Linux compatible?

### ISSUE THREAD

**Issue by xcom169** [gereons/AoCTools#1]
Hello, 
I really like your solution however I can't run it on Linux.  Is it possible to make it cross platform?

<code>
Fetching https://github.com/gereons/AoCTools from cache
Fetching https://github.com/lukepistrol/SwiftLintPlugin from cache
Fetched https://github.com/lukepistrol/SwiftLintPlugin from cache (0.43s)
Fetched https://github.com/gereons/AoCTools from cache (0.43s)
Computing version for https://github.com/gereons/AoCTools
Computed https://github.com/gereons/AoCTools at 0.0.45 (0.02s)
Computing version for https://github.com/lukepistrol/SwiftLintPlugin
Computed https://github.com/lukepistrol/SwiftLintPlugin at 0.54.0 (0.02s)
Creating working copy for https://github.com/lukepistrol/SwiftLintPlugin
Working copy of https://github.com/lukepistrol/SwiftLintPlugin resolved at 0.54.0
Creating working copy for https://github.com/gereons/AoCTools
Working copy of https://github.com/gereons/AoCTools resolved at 0.0.45
Downloading binary artifact https://github.com/realm/SwiftLint/releases/download/0.54.0/SwiftLintBinary-macos.artifactbundle.zip
error: failed downloading 'https://github.com/realm/SwiftLint/releases/download/0.54.0/SwiftLintBinary-macos.artifactbundle.zip' which is required by binary target 'SwiftLintBinary': downloadError("Error Domain=NSURLErrorDomain Code=-1001 \"(null)\"")
error: fatalError

</code>

**Comment by gereons** [comment]
I'm sorry, I don't have access to a Linux machine with Swift installed, so I wouldn't be able to run/test in such an environment. Also, as far as I can tell, neither SwiftLint nor SwiftLintPlugin are currently available for Linux, and that's where your error comes from, and I would rather like to keep using SwiftLint.

I would, however, welcome PRs that add Linux capabilities while preserving the current API and usage of SwiftLint when building on macOS.

**Comment by xcom169** [comment]
Okay. Thanks
